/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.smartbit4all.platform.gradle

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'org.smartbit4ll.platform.gradle.greeting' plugin.
 */
public class PlatformGradlePluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("org.smartbit4ll.platform.gradle.java")

        then:
        project.tasks.findByName("jar") != null
    }
}
