/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.smartbit4all.platform.gradle

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner

/**
 * A simple functional test for the 'org.smartbit4ll.platform.gradle.greeting' plugin.
 */
public class PlatformGradlePluginFunctionalTest extends Specification {
    // TODO test plugins..
//    def "can run task"() {
//        given:
//        def projectDir = new File("build/functionalTest")
//        projectDir.mkdirs()
//        new File(projectDir, "settings.gradle") << ""
//        new File(projectDir, "build.gradle") << """
//            plugins {
//                id('org.smartbit4ll.platform.gradle.greeting')
//            }
//        """
//
//        when:
//        def runner = GradleRunner.create()
//        runner.forwardOutput()
//        runner.withPluginClasspath()
//        runner.withArguments("greeting")
//        runner.withProjectDir(projectDir)
//        def result = runner.build()
//
//        then:
//        result.output.contains("Hello from plugin 'org.smartbit4ll.platform.gradle.greeting'")
//    }
}
